baseurl = "http://archs.github.io/"
languageCode = "en-us"
title = "Archs"
disqusShortname = "archs"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  highlight = "monokai"
  author = "Archs Sun"